baseurl = 'https://dai08srhg.github.io/portfolio/'
DefaultContentLanguage = "en"
title = "HOME ğŸˆ"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "DaisukeFukushima"
  subtitle = "â‚Ë„Â·Íˆà¼Â·ÍˆË„â‚ â‚Ë„Â·Íˆà¼Â·ÍˆË„â‚ â‚Ë„Â·Íˆà¼Â·ÍˆË„â‚à¸…Ë’Ë’"
  mainSections = ["page"]
  logo = "img/icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employerâ€™s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Fukushima"
  website = "yourwebsite.com"
  github = "dai08srhg"
  twitter = "@igx63je2"
  linkedin = "fukushima-ab"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    identifier = "contents"
    name = "contents"
    weight = 2

[[menu.main]]
    parent = "contents"
    name = "tech post"
    url = "post/"
    weight = 1

[[menu.main]]
    parent = "contents"
    name = "paper database"
    url = "https://juicy-cookie-078.notion.site/Paper-Database-ff354caa71fb42f9b196d203c9dcf587?pvs=4"
    weight = 2

[[menu.main]]
    parent = "contents"
    name = "â‚Ë„Â·Íˆà¼Â·ÍˆË„â‚à¸…Ë’Ë’"
    url = "gallary/gallary"
    weight = 3
